package net.hawry.messaging.core;

public enum MessageTagType {
  ALERT("COMMUNITY_ALERT"), EVENT_REMINDER("CONFIRMED_EVENT_REMINDER"), NON_PROMO_SUBSCRIPTION("NON_PROMOTIONAL_SUBSCRIPTION"), PAIRING_UPDATE("PAIRING_UPDATE"), APP_UPDATE("APPLICATION_UPDATE"), PAYMENT_UPDATE("PAYMENT_UPDATE"), FINANCE_UPDATE("PERSONAL_FINANCE_UPDATE"), SHIPPING_UPDATE("SHIPPING_UPDATE"), RESERVATION_UPDATE("RESERVATION_UPDATE"), ISSUE_RESOLUTION("ISSUE_RESOLUTION"), APPOINTMENT_UPDATE("APPOINTMENT_UPDATE"), GAME_EVENT("GAME_EVENT"), TRANSPORT_UPDATE("TRANSPORTATION_UPDATE"), FUNC_UPDATE("FEATURE_FUNCTIONALITY_UPDATE"),TICKET_UPDATE("TICKET_UPDATE");
  private String value;
  MessageTagType(String v) {
    value = v;
  }
  protected String getValue() {
    return value;
  }
}